name: Unit testing

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "master" ]
    tags: [ "*" ]

jobs:
  default:
    uses: ./.github/workflows/reusable-testing.yml
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-20.04
          - ubuntu-22.04
          - macos-11
          - macos-12
        build-type:
          - Debug
          - ReleaseWithDebInfo
    with:
      runs-on: ${{ matrix.runs-on }}
      build-type: ${{ matrix.runs-on }}
